server:
  port: 8082

spring:
  application:
    name: basket
  datasource:
    username: postgres
    password: postgresql
    url: jdbc:postgresql://localhost:5432/productStore
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true